# Day 1

In [ ]:
https://github.com/c17hawke/Perceptron_implimentation_FSDS

In [3]:
!pip install joblib

In [21]:
import os
import pandas as pd
import matplotlib.pyplot as plt
import joblib
import numpy as np

plt.style.use('fivethirtyeight')

In [29]:
class Perceptron:
    def __init__(self, eta: float=None, epochs: int=None):
        self.weights = np.random.randn(3) * 1e-4
        self.eta = eta # Learning rate
        self.epochs = epochs # iterations
    
    def _z_outcome(self, inputs, weights):
        return np.dot(inputs, weights)
    
    def activation_function(self,z):
        return np.where(z > 0, 1, 0)
        
    def fit(self, x, y):
        self.x = x
        self.y = y
        
        x_with_bias = np.c_[self.x, -np.ones((len(self.x),1))]
        print(f"X with bias: \n{x_with_bias}")
        
        for epoch in range(self.epochs):
            print("--"*10)
            print(f"for epoch >> {epoch+1}")
            print("--"*10)
            
            z = self._z_outcome(x_with_bias, self.weights)
            y_hat = self.activation_function(z)
            print(f"Predicted value after forward pass: \n{y_hat}")
            
            self.error = self.y - y_hat
            print(f"error: \n{self.error}")
            
            self.weights = self.weights + self.eta * np.dot(x_with_bias.T, self.error)
            print(f"updated weights afetr epoch: {epoch+1}/{self.epochs}: \n{self.weights}")
            print(f"##"*10)
            
    def predict(self,x):
        x_with_bias = np.c_[x, -np.ones((len(x), 1))]
        z = self._z_outcome(x_with_bias, self.weights)
        return self.activation_function(z)

In [22]:
OR = {
    'x1':[0,0,1,1],
    'x2':[0,1,0,1],
    'y':[0,1,1,1]
}

df_OR = pd.DataFrame(OR)

df_OR

x1  x2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  1

In [23]:
def prepare_data(df, target_col='y'):
    x = df.drop(target_col, axis=1)
    y = df[target_col]
    
    return x,y

In [30]:
x, y = prepare_data(df_OR)

ETA = 0.1
EPOCHS = 10

model_or = Perceptron(eta=ETA, epochs=EPOCHS)

model_or.fit(x,y)

X with bias: 
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
--------------------
for epoch >> 1
--------------------
Predicted value after forward pass: 
[0 0 0 0]
error: 
0    0
1    1
2    1
3    1
Name: y, dtype: int64
updated weights afetr epoch: 1/10: 
[ 0.20000127  0.19985242 -0.29988857]
####################
--------------------
for epoch >> 2
--------------------
Predicted value after forward pass: 
[1 1 1 1]
error: 
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
updated weights afetr epoch: 2/10: 
[ 0.20000127  0.19985242 -0.19988857]
####################
--------------------
for epoch >> 3
--------------------
Predicted value after forward pass: 
[1 1 1 1]
error: 
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
updated weights afetr epoch: 3/10: 
[ 0.20000127  0.19985242 -0.09988857]
####################
--------------------
for epoch >> 4
--------------------
Predicted value after forward pass: 
[1 1 1 1]
error: 
0   -1
1    0
2    0
3    0
Name: y, dtype

In [28]:
model_or.predict(x=[[1,0]])

array([1])

In [36]:
AND = {
    'x1':[0,0,1,1],
    'x2':[0,1,0,1],
    'y':[0,0,0,1]
}

df_AND = pd.DataFrame(AND)

df_AND

x, y = prepare_data(df_AND)

ETA = 0.1
EPOCHS = 10

model_and = Perceptron(eta=ETA, epochs=EPOCHS)

model_and.fit(x,y)

X with bias: 
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
--------------------
for epoch >> 1
--------------------
Predicted value after forward pass: 
[1 1 1 1]
error: 
0   -1
1   -1
2   -1
3    0
Name: y, dtype: int64
updated weights afetr epoch: 1/10: 
[-0.10004277 -0.10009776  0.29975745]
####################
--------------------
for epoch >> 2
--------------------
Predicted value after forward pass: 
[0 0 0 0]
error: 
0    0
1    0
2    0
3    1
Name: y, dtype: int64
updated weights afetr epoch: 2/10: 
[-4.27720690e-05 -9.77630286e-05  1.99757452e-01]
####################
--------------------
for epoch >> 3
--------------------
Predicted value after forward pass: 
[0 0 0 0]
error: 
0    0
1    0
2    0
3    1
Name: y, dtype: int64
updated weights afetr epoch: 3/10: 
[0.09995723 0.09990224 0.09975745]
####################
--------------------
for epoch >> 4
--------------------
Predicted value after forward pass: 
[0 1 1 1]
error: 
0    0
1   -1
2   -1
3    0
Name:

In [35]:
XOR = {
    'x1':[0,0,1,1],
    'x2':[0,1,0,1],
    'y':[0,1,1,0]
}

df_XOR = pd.DataFrame(XOR)

df_XOR

x, y = prepare_data(df_XOR)

ETA = 0.1
EPOCHS = 10

model_xor = Perceptron(eta=ETA, epochs=EPOCHS)

model_xor.fit(x,y)

X with bias: 
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
--------------------
for epoch >> 1
--------------------
Predicted value after forward pass: 
[1 1 1 1]
error: 
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
updated weights afetr epoch: 1/10: 
[-0.09990851 -0.10001052  0.19994083]
####################
--------------------
for epoch >> 2
--------------------
Predicted value after forward pass: 
[0 0 0 0]
error: 
0    0
1    1
2    1
3    0
Name: y, dtype: int64
updated weights afetr epoch: 2/10: 
[ 9.14925710e-05 -1.05175766e-05 -5.91731462e-05]
####################
--------------------
for epoch >> 3
--------------------
Predicted value after forward pass: 
[1 1 1 1]
error: 
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
updated weights afetr epoch: 3/10: 
[-0.09990851 -0.10001052  0.19994083]
####################
--------------------
for epoch >> 4
--------------------
Predicted value after forward pass: 
[0 0 0 0]
error: 
0    0
1    1
2    1
3    0
Na

In [38]:
NAND = {
    'x1':[0,0,1,1],
    'x2':[0,1,0,1],
    'y':[1,0,0,0]
}

df_NAND = pd.DataFrame(NAND)

df_NAND

x, y = prepare_data(df_NAND)

ETA = 0.1
EPOCHS = 10

model_nand = Perceptron(eta=ETA, epochs=EPOCHS)

model_nand.fit(x,y)

X with bias: 
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
--------------------
for epoch >> 1
--------------------
Predicted value after forward pass: 
[1 1 1 1]
error: 
0    0
1   -1
2   -1
3   -1
Name: y, dtype: int64
updated weights afetr epoch: 1/10: 
[-0.19994497 -0.19982192  0.2999141 ]
####################
--------------------
for epoch >> 2
--------------------
Predicted value after forward pass: 
[0 0 0 0]
error: 
0    1
1    0
2    0
3    0
Name: y, dtype: int64
updated weights afetr epoch: 2/10: 
[-0.19994497 -0.19982192  0.1999141 ]
####################
--------------------
for epoch >> 3
--------------------
Predicted value after forward pass: 
[0 0 0 0]
error: 
0    1
1    0
2    0
3    0
Name: y, dtype: int64
updated weights afetr epoch: 3/10: 
[-0.19994497 -0.19982192  0.0999141 ]
####################
--------------------
for epoch >> 4
--------------------
Predicted value after forward pass: 
[0 0 0 0]
error: 
0    1
1    0
2    0
3    0
Name: y, dtype